//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_4_2.AutoCompleteServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoCompleteServiceReference.AutoCompleteServiceSoap")]
    public interface AutoCompleteServiceSoap {
        
        // CODEGEN: Generating message contract since element name prefixText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFriends", ReplyAction="*")]
        Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponse SearchFriends(Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFriends", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponse> SearchFriendsAsync(Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchFriendsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchFriends", Namespace="http://tempuri.org/", Order=0)]
        public Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequestBody Body;
        
        public SearchFriendsRequest() {
        }
        
        public SearchFriendsRequest(Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchFriendsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prefixText;
        
        public SearchFriendsRequestBody() {
        }
        
        public SearchFriendsRequestBody(string prefixText) {
            this.prefixText = prefixText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchFriendsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchFriendsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponseBody Body;
        
        public SearchFriendsResponse() {
        }
        
        public SearchFriendsResponse(Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchFriendsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment_4_2.AutoCompleteServiceReference.ArrayOfString SearchFriendsResult;
        
        public SearchFriendsResponseBody() {
        }
        
        public SearchFriendsResponseBody(Assignment_4_2.AutoCompleteServiceReference.ArrayOfString SearchFriendsResult) {
            this.SearchFriendsResult = SearchFriendsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoCompleteServiceSoapChannel : Assignment_4_2.AutoCompleteServiceReference.AutoCompleteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoCompleteServiceSoapClient : System.ServiceModel.ClientBase<Assignment_4_2.AutoCompleteServiceReference.AutoCompleteServiceSoap>, Assignment_4_2.AutoCompleteServiceReference.AutoCompleteServiceSoap {
        
        public AutoCompleteServiceSoapClient() {
        }
        
        public AutoCompleteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoCompleteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoCompleteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponse Assignment_4_2.AutoCompleteServiceReference.AutoCompleteServiceSoap.SearchFriends(Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest request) {
            return base.Channel.SearchFriends(request);
        }
        
        public Assignment_4_2.AutoCompleteServiceReference.ArrayOfString SearchFriends(string prefixText) {
            Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest inValue = new Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest();
            inValue.Body = new Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequestBody();
            inValue.Body.prefixText = prefixText;
            Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponse retVal = ((Assignment_4_2.AutoCompleteServiceReference.AutoCompleteServiceSoap)(this)).SearchFriends(inValue);
            return retVal.Body.SearchFriendsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponse> Assignment_4_2.AutoCompleteServiceReference.AutoCompleteServiceSoap.SearchFriendsAsync(Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest request) {
            return base.Channel.SearchFriendsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment_4_2.AutoCompleteServiceReference.SearchFriendsResponse> SearchFriendsAsync(string prefixText) {
            Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest inValue = new Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequest();
            inValue.Body = new Assignment_4_2.AutoCompleteServiceReference.SearchFriendsRequestBody();
            inValue.Body.prefixText = prefixText;
            return ((Assignment_4_2.AutoCompleteServiceReference.AutoCompleteServiceSoap)(this)).SearchFriendsAsync(inValue);
        }
    }
}
